### ISSUE TITLE
Migrate to monorepo and `@hono/sentry`

### ISSUE THREAD

**Issue by yusukebe** [honojs/sentry#12]
Hi @sam-lippert !

We are going to do three things:

1. Manage this middleware under the [middleware monorepo](https://github.com/honojs/middleware). ref: [hono#601](https://github.com/honojs/hono/issues/601)
2. Publish this middleware as `@hono/sentry`. ref: [hono#738](https://github.com/honojs/hono/issues/738)
3. Have Deno users use `npm:@hono/sentry`.

So, can you let me do these things? I'll try to move the repository while keeping Git history. After the migration is complete, you can keep maintaining the project.

**Comment by sam-lippert** [comment]
Sounds great! Thanks for the heads up.

**Comment by yusukebe** [comment]
Hi @sam-lippert 

I've finished the migrations:

1. Moving to the monorepo.
2. Rename to `@hono/sentry`.

Now, let's do the development on the following the monorepo:

https://github.com/honojs/middleware/tree/main/packages/sentry

And I'll archive this repository later. Thanks!
