### ISSUE TITLE
sentry.captureException(error) is not called

### ISSUE THREAD

**Issue by pensuke81** [honojs/sentry#3]
It seems that `sentry.captureException(error)` does not call.
I tested with Cloudflare Worker.

https://github.com/honojs/sentry/blob/ca742a2ea35808cf2b70a19407a93481b4fbe8a0/src/index.ts#L51-L56

It works if I write `c.get('sentry').captureException(error)` in app.OnError in my application.
( Also c.get('sentry') is undefined, so it looks like `c.set('sentry', sentry)` is also needed. )

I'm using hono: v2.1.2.

**Comment by yusukebe** [comment]
Hi @pensuke81 !

Thank you for creating the issue. This bug is caused by Hono itself. I've fixed the issue in this PR: https://github.com/honojs/hono/pull/491

We will soon merge this PR and release a new version, then this bug might be fixed. so please wait a bit.

**Comment by yusukebe** [comment]
@pensuke81 

We've released [v2.1.3](https://github.com/honojs/hono/releases/tag/v2.1.3) just now. Please try Sentry middleware with this version of Hono. Please let me know if this upgrade doesn't seem to solve the problem.

**Comment by Zerebokep** [comment]
getSentry(c) and c.get('sentry') is still undefined on my end.

**Comment by pensuke81** [comment]
@yusukebe 
It worked with v2.1.3. Thank you!

> getSentry(c) and c.get('sentry') is still undefined on my end.

This is a different issue, but also on my end.
should create a new issue?

**Comment by yusukebe** [comment]
@pensuke81 

> should create a new issue?

Yes, please.

---

@sam-lippert Can you fix that issue? Or shall I create the PR?

**Comment by pensuke81** [comment]
I've created a new issue about `getSentry(c)` #5 so this issue is now resolved.
Thank you!

**Comment by sam-lippert** [comment]
@yusukebe Yes, I can take a look at that. I'll self-assign https://github.com/honojs/sentry/issues/5
