### ISSUE TITLE
getSentry(c) is undefined

### ISSUE THREAD

**Issue by pensuke81** [honojs/sentry#5]
`getSentry(c)` is exported but it seems to be undefined.
https://github.com/honojs/sentry/blob/ca742a2ea35808cf2b70a19407a93481b4fbe8a0/src/index.ts#L60-L62

**Comment by sam-lippert** [comment]
@yusukebe @pensuke81 @Zerebokep This should now be fixed by commit https://github.com/honojs/sentry/commit/8e290c0b70273f2f0ba12c018e6a71d3158ffb1f and version @0.0.2

**Comment by Zerebokep** [comment]
Still seems to be undefined on my end. It works when I set sentry manually in a middleware.
