### ISSUE TITLE
Hono should be a peer dependency

### ISSUE THREAD

**Issue by danew** [honojs/sentry#8]
Having an issue with a type mismatch due to this package depending on a different version of hono. They can easily be fix by changing it to a peer dependency.

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/5265684/207031443-9fc3f4af-0d85-4d10-810e-00260644e77a.png">

Solution: 
<img width="308" alt="image" src="https://user-images.githubusercontent.com/5265684/207031711-3fea0406-a8b9-4b93-8b5a-ab317a1d3843.png">

<img width="427" alt="image" src="https://user-images.githubusercontent.com/5265684/207031754-53832bca-b721-4aca-8dd8-1c40b8bf7185.png">

**Comment by yusukebe** [comment]
This closed by #9
